### ISSUE TITLE
 NoMethodError: undefined method `encode' for CGI:Class

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-worker#1]
Found this is builder logs:

2016-02-05T20:02:14.000990479Z + rm -rf /home/omv/libcap
2016-02-05T20:02:14.000996412Z + sudo pkill -TERM -P 10693
2016-02-05T20:02:14.001002332Z + exit
2016-02-05T20:02:14.025089291Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2016-02-05T20:02:14.025125290Z                                  Dload  Upload   Total   Spent    Left  Speed
2016-02-05T20:02:14.047044333Z    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100     2    0     2    0     0     46      0 --:--:-- --:--:-- --:--:--    95
2016-02-05T20:02:14.047949452Z rake aborted!
2016-02-05T20:02:14.048003475Z NoMethodError: undefined method `encode' for CGI:Class
2016-02-05T20:02:14.048035727Z /home/omv/docker-worker/lib/docker-rpm-worker/base_worker.rb:85:in`upload_file_to_file_store'
2016-02-05T20:02:14.048047407Z /home/omv/docker-worker/lib/docker-rpm-worker/base_worker.rb:101:in `block in upload_results_to_file_store'
2016-02-05T20:02:14.048057107Z /home/omv/docker-worker/lib/docker-rpm-worker/base_worker.rb:100:in`each'
2016-02-05T20:02:14.048066184Z /home/omv/docker-worker/lib/docker-rpm-worker/base_worker.rb:100:in `upload_results_to_file_store'
2016-02-05T20:02:14.048075470Z /home/omv/docker-worker/lib/docker-rpm-worker/rpm_worker.rb:28:in`send_results'
2016-02-05T20:02:14.048084522Z /home/omv/docker-worker/lib/docker-rpm-worker/base_worker.rb:36:in `perform'
2016-02-05T20:02:14.048093795Z /home/omv/docker-worker/lib/docker-rpm-worker/task_manager.rb:58:in`block in find_new_job'
2016-02-05T20:02:14.048108691Z Tasks: TOP => abf_worker:start

**Comment by avokhmin** [comment]
[#upload_file_to_file_store](https://github.com/OpenMandrivaSoftware/docker-worker/blob/master/lib/docker-rpm-worker/base_worker.rb#L79-L89)

maybe:

```
force_encoding('UTF-8').encode('UTF-8', invalid: :replace)
```

**Comment by DuratarskeyK** [comment]
Fixed
